### ISSUE TITLE
npm run serve 错误

### ISSUE THREAD

**Issue by chenxuezhou** [tobeapro/shop-mall-app#1]
These dependencies were not found:

* core-js/modules/es6.array.find in ./src/store/modules/shop.js
* core-js/modules/web.dom.iterable in ./node_modules/cache-loader/dist/cjs.js??r
ef--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js
??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/vi
ews/shopCar.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save core-js/modules/es6.array.find
core-js/modules/web.dom.iterable

**Comment by chenxuezhou** [comment]
我使用的是webpack

**Comment by tobeapro** [comment]
:joy:  这问题应该和资源包版本有关，建议使用yarn安装依赖，可以看yarn.lock中的各个依赖的版本号或者自己写死版本号再安装
